CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS locations
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat REAL NOT NULL,
    lon REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS events
(
    annotation           VARCHAR(2000)                     NOT NULL,
    category_id          BIGINT REFERENCES categories (id) NOT NULL,
    created_on           TIMESTAMP WITHOUT TIME ZONE       NOT NULL,
    description          VARCHAR(7000)                     NOT NULL,
    event_date           TIMESTAMP WITHOUT TIME ZONE       NOT NULL,
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    initiator_id         BIGINT                            NOT NULL REFERENCES users (id) ON DELETE NO ACTION,
    location_id          BIGINT                            NOT NULL REFERENCES locations (id) ON DELETE NO ACTION,
    is_paid              BOOLEAN                           NOT NULL,
    participant_limit    INT                               NOT NULL,
    published_on         TIMESTAMP WITHOUT TIME ZONE       NULL,
    is_request_moderated BOOLEAN                           NOT NULL,
    state                INT                               NOT NULL,
    title                VARCHAR(120)                      NOT NULL
);



CREATE TABLE IF NOT EXISTS requests
(
    created      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    event_id     BIGINT                      NOT NULL REFERENCES events (id),
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_id BIGINT                      NOT NULL REFERENCES users (id),
    status       INT                         NOT NULL
);

CREATE TABLE IF NOT EXISTS compilations
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_pinned BOOLEAN NOT NULL,
    title     VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS events_compilations
(
    event_id       BIGINT NOT NULL REFERENCES events (id),
    compilation_id BIGINT NOT NULL REFERENCES compilations (id)
);

CREATE TABLE IF NOT EXISTS comments
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT                      NOT NULL REFERENCES users (id),
    event_id        BIGINT                      NOT NULL REFERENCES events (id),
    text_of_comment VARCHAR(1000)               NOT NULL,
    created         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status          VARCHAR                     NOT NULL
);