CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name  VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    CONSTRAINT pk_users_id PRIMARY KEY (id),
    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    CONSTRAINT pk_categories_id PRIMARY KEY (id),
    CONSTRAINT uq_categories_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS locations
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    lat REAL NOT NULL,
    lon REAL NOT NULL,
    CONSTRAINT pk_locations_id PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events
(
    annotation           VARCHAR(2000)               NOT NULL,
    category_id          BIGINT                      NOT NULL,
    creates_on           TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    description          VARCHAR(7000)               NOT NULL,
    event_date           TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    initiator_id         BIGINT                      NOT NULL,
    location_id          BIGINT                      NOT NULL,
    is_paid              BOOLEAN                     NOT NULL,
    participant_limit    INT                         NOT NULL,
    published_on         TIMESTAMP WITHOUT TIME ZONE,
    is_request_moderated BOOLEAN                     NOT NULL,
    state                INT                         NOT NULL,
    title                VARCHAR(120)                NOT NULL,
    CONSTRAINT pk_events_id PRIMARY KEY (id),
    CONSTRAINT fk_events_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT fk_events_initiator_id FOREIGN KEY (initiator_id) REFERENCES users (id),
    CONSTRAINT fk_events_locations_id FOREIGN KEY (location_id) REFERENCES locations (id)
);



CREATE TABLE IF NOT EXISTS requests
(
    created      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    event_id     BIGINT                      NOT NULL,
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    requester_id BIGINT                      NOT NULL,
    status       INT                         NOT NULL,
    CONSTRAINT pk_requests_id PRIMARY KEY (id),
    CONSTRAINT fk_event_id FOREIGN KEY (event_id) REFERENCES events (id),
    CONSTRAINT fk_requester_id FOREIGN KEY (requester_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS compilations
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    is_pinned BOOLEAN NOT NULL,
    title     VARCHAR NOT NULL,
    CONSTRAINT pk_compilations_id PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events_compilations
(
    event_id       BIGINT NOT NULL,
    compilation_id BIGINT NOT NULL,
    CONSTRAINT fk_events_compilations_event_id FOREIGN KEY (event_id) REFERENCES events (id),
    CONSTRAINT fk_events_compilations_compilation_id FOREIGN KEY (compilation_id) REFERENCES compilations (id)
);