version: '3.1'
services:
  stat-server:
    build: stat-service/
    container_name: stat_server
    ports:
      - "9090:9090"
    depends_on: [stats-db]
    environment:
      - POSTGRES_USER=stat
      - POSTGRES_PASSWORD=stat

  stats-db:
    image: postgres:14-alpine
    container_name: stat_db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=statsDb
      - POSTGRES_USER=stat
      - POSTGRES_PASSWORD=stat

  ewm-service:
    build: main-service/
    container_name: main_server
    ports:
      - "8080:8080"
    depends_on: [ewm-db]
    environment:
      - POSTGRES_USER=main
      - POSTGRES_PASSWORD=main
      - STAT_SERVER=http://localhost:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: main_db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=mainDb
      - POSTGRES_USER=main
      - POSTGRES_PASSWORD=main
