CREATE TABLE IF NOT EXISTS endpointhits
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    app          VARCHAR                     NOT NULL,
    uri          VARCHAR                     NOT NULL,
    ip           VARCHAR                     NOT NULL,
    request_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_endpointhits_id PRIMARY KEY (id)
);