CREATE TABLE IF NOT EXISTS endpointhits
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    app          VARCHAR  NOT NULL,
    uri          VARCHAR  NOT NULL,
    ip           VARCHAR  NOT NULL,
    request_time DATETIME NOT NULL,
    CONSTRAINT pk_endpointhits_id PRIMARY KEY (id)
);